window:
  padding:
    x: 10
    y: 10
  decorations: full
  opacity: 1.0

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Medium

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: IJetBrainsMono Nerd Font
    style: Italic

  size: 10.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

custom_cursor_colors: true

colors:
  primary:
    background: '#1a1a1a'
    foreground: '#ccd1d5'
  normal:
    black:   '#101010'
    red:     '#d57c74'
    green:   '#7ca09f'
    yellow:  '#d6a288'
    blue:    '#536d92'
    magenta: '#8b6587'
    cyan:    '#779ba7'
    white:   '#ccd1d5'
  bright:
    black:   '#5e5e5e'
    red:     '#ffb2a2'
    green:   '#a4dbd0'
    yellow:  '#ffd4b4'
    blue:    '#6b83ac'
    magenta: '#a787a7'
    cyan:    '#99bcc9'
    white:   '#ffffff'


      #key_bindings:
      #{ key:  U, mods: Control|Shift, action: ScrollPageUp },
      #{ key:  D, mods:  Control|Shift, action:  ScrollPageDown },

mouse:
  hide_when_typing: true
cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style:
    shape: Block
    blinking: On

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#shell:
#  program: /usr/local/bin/fish
#  args:
#    - --command=tmux

# vim: nospell
