window:
  padding:
    x: 10
    y: 10
  decorations: full
  opacity: 1.0

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Medium

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: IJetBrainsMono Nerd Font
    style: Italic

  size: 10.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

custom_cursor_colors: true

  # Colores (Vesper)
colors:
  primary:
    background: '#101010'
    foreground: '#ffffff'

  normal:
    black:   '#101010'
    red:     '#f5a191'
    green:   '#90b99f'
    yellow:  '#e6b99d'
    blue:    '#aca1cf'
    magenta: '#e29eca'
    cyan:    '#ea83a5'
    white:   '#a0a0a0'

  bright:
    black:   '#7e7e7e'
    red:     '#ff8080'
    green:   '#99ffe4'
    yellow:  '#ffc799'
    blue:    '#b9aeda'
    magenta: '#ecaad6'
    cyan:    '#f591b2'
    white:   '#ffffff'


      #key_bindings:
      #{ key:  U, mods: Control|Shift, action: ScrollPageUp },
      #{ key:  D, mods:  Control|Shift, action:  ScrollPageDown },

mouse:
  hide_when_typing: true
cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style:
    shape: Beam
    blinking: On

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#shell:
#  program: /usr/local/bin/fish
#  args:
#    - --command=tmux

# vim: nospell
