require("plugins")
require("keybindings")
require("options")
require("nvim-tree-config")
require("lualine-config")
require("bufferline-config")
require("treesitter-config")
require("autopairs-config")
require("whichkey-config")
require("telescope-config")
require("colorizer-config")
require("blankline-config")
require("null-ls-config")
require("toggleterm-config")
require("comment-config")
require("theme-config")
require("zen-mode-config")
-- require('twilight-config')
require("lsp")
vim.cmd("colorscheme carbonfox")
